p = struct();
p.input_dir = 'C:\Users\Peter\Documents\MATLAB\matlab-expectation-models\media\example-wav-files';
p.output_dir = 'C:\Users\Peter\Documents\MATLAB\temp';
p.onsets = 0:2;
p.offsets = 1:3;
p.use_closure = true;
p.leman_2000_local_decay_sec = [0.1 0.5];
p.leman_2000_global_decay_sec = [1.5 4];

analyse_dataset(...
    p.input_dir, ...
    p.output_dir, ...
    p.onsets, ...
    p.offsets, ...
    p.use_closure, ...
    p.leman_2000_local_decay_sec, ...
    p.leman_2000_global_decay_sec);




% input_file = 'id=1_genre=classical_c-id=1009_e-id=75_ic_category_1.wav';
% [leman, collins, collins_detail] = analyse_sequence(input_file, input_dir, params, jlmtpath);