function [leman, collins, collins_detail] = analyse_sequence(...
    wav_file, ...
    wav_dir, ...
    onsets, ...
    offsets, ...
    leman_2000_local_decay_sec, ...
    leman_2000_global_decay_sec, ...
    jlmtpath)

% Returns a 1 x N array corresponding to the N onsets/offsets
leman = leman_2000(...
    wav_file, ...
    wav_dir, ...
    onsets, offsets, ...
    leman_2000_local_decay_sec, ...
    leman_2000_global_decay_sec);

[collins, collins_detail] = collins_2014(wav_file, ...
    wav_dir, ...
    par.target_chord_index, ...
    par.audio_leading_time_delay_sec, ...
    par.tempo, ...
    jlmtpath, ...
    par.collins2014_use_closure);

end